package com.demo.druid.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogPageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public LogPageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPaopidIsNull() {
            addCriterion("PAOPID is null");
            return (Criteria) this;
        }

        public Criteria andPaopidIsNotNull() {
            addCriterion("PAOPID is not null");
            return (Criteria) this;
        }

        public Criteria andPaopidEqualTo(Integer value) {
            addCriterion("PAOPID =", value, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidNotEqualTo(Integer value) {
            addCriterion("PAOPID <>", value, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidGreaterThan(Integer value) {
            addCriterion("PAOPID >", value, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAOPID >=", value, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidLessThan(Integer value) {
            addCriterion("PAOPID <", value, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidLessThanOrEqualTo(Integer value) {
            addCriterion("PAOPID <=", value, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidIn(List<Integer> values) {
            addCriterion("PAOPID in", values, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidNotIn(List<Integer> values) {
            addCriterion("PAOPID not in", values, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidBetween(Integer value1, Integer value2) {
            addCriterion("PAOPID between", value1, value2, "paopid");
            return (Criteria) this;
        }

        public Criteria andPaopidNotBetween(Integer value1, Integer value2) {
            addCriterion("PAOPID not between", value1, value2, "paopid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseripIsNull() {
            addCriterion("USERIP is null");
            return (Criteria) this;
        }

        public Criteria andUseripIsNotNull() {
            addCriterion("USERIP is not null");
            return (Criteria) this;
        }

        public Criteria andUseripEqualTo(String value) {
            addCriterion("USERIP =", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotEqualTo(String value) {
            addCriterion("USERIP <>", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripGreaterThan(String value) {
            addCriterion("USERIP >", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripGreaterThanOrEqualTo(String value) {
            addCriterion("USERIP >=", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripLessThan(String value) {
            addCriterion("USERIP <", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripLessThanOrEqualTo(String value) {
            addCriterion("USERIP <=", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripLike(String value) {
            addCriterion("USERIP like", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotLike(String value) {
            addCriterion("USERIP not like", value, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripIn(List<String> values) {
            addCriterion("USERIP in", values, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotIn(List<String> values) {
            addCriterion("USERIP not in", values, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripBetween(String value1, String value2) {
            addCriterion("USERIP between", value1, value2, "userip");
            return (Criteria) this;
        }

        public Criteria andUseripNotBetween(String value1, String value2) {
            addCriterion("USERIP not between", value1, value2, "userip");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameIsNull() {
            addCriterion("LAST_ACTION_ENAME is null");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameIsNotNull() {
            addCriterion("LAST_ACTION_ENAME is not null");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME =", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameNotEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME <>", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameGreaterThan(String value) {
            addCriterion("LAST_ACTION_ENAME >", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME >=", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameLessThan(String value) {
            addCriterion("LAST_ACTION_ENAME <", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameLessThanOrEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME <=", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameLike(String value) {
            addCriterion("LAST_ACTION_ENAME like", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameNotLike(String value) {
            addCriterion("LAST_ACTION_ENAME not like", value, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameIn(List<String> values) {
            addCriterion("LAST_ACTION_ENAME in", values, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameNotIn(List<String> values) {
            addCriterion("LAST_ACTION_ENAME not in", values, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameBetween(String value1, String value2) {
            addCriterion("LAST_ACTION_ENAME between", value1, value2, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionEnameNotBetween(String value1, String value2) {
            addCriterion("LAST_ACTION_ENAME not between", value1, value2, "lastActionEname");
            return (Criteria) this;
        }

        public Criteria andLastActionIdIsNull() {
            addCriterion("LAST_ACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andLastActionIdIsNotNull() {
            addCriterion("LAST_ACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLastActionIdEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID =", value, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdNotEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID <>", value, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdGreaterThan(Integer value) {
            addCriterion("LAST_ACTION_ID >", value, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID >=", value, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdLessThan(Integer value) {
            addCriterion("LAST_ACTION_ID <", value, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdLessThanOrEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID <=", value, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdIn(List<Integer> values) {
            addCriterion("LAST_ACTION_ID in", values, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdNotIn(List<Integer> values) {
            addCriterion("LAST_ACTION_ID not in", values, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdBetween(Integer value1, Integer value2) {
            addCriterion("LAST_ACTION_ID between", value1, value2, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andLastActionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("LAST_ACTION_ID not between", value1, value2, "lastActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameIsNull() {
            addCriterion("CUR_ACTION_ENAME is null");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameIsNotNull() {
            addCriterion("CUR_ACTION_ENAME is not null");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME =", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameNotEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME <>", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameGreaterThan(String value) {
            addCriterion("CUR_ACTION_ENAME >", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameGreaterThanOrEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME >=", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameLessThan(String value) {
            addCriterion("CUR_ACTION_ENAME <", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameLessThanOrEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME <=", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameLike(String value) {
            addCriterion("CUR_ACTION_ENAME like", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameNotLike(String value) {
            addCriterion("CUR_ACTION_ENAME not like", value, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameIn(List<String> values) {
            addCriterion("CUR_ACTION_ENAME in", values, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameNotIn(List<String> values) {
            addCriterion("CUR_ACTION_ENAME not in", values, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameBetween(String value1, String value2) {
            addCriterion("CUR_ACTION_ENAME between", value1, value2, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionEnameNotBetween(String value1, String value2) {
            addCriterion("CUR_ACTION_ENAME not between", value1, value2, "curActionEname");
            return (Criteria) this;
        }

        public Criteria andCurActionIdIsNull() {
            addCriterion("CUR_ACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andCurActionIdIsNotNull() {
            addCriterion("CUR_ACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCurActionIdEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID =", value, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdNotEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID <>", value, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdGreaterThan(Integer value) {
            addCriterion("CUR_ACTION_ID >", value, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID >=", value, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdLessThan(Integer value) {
            addCriterion("CUR_ACTION_ID <", value, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdLessThanOrEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID <=", value, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdIn(List<Integer> values) {
            addCriterion("CUR_ACTION_ID in", values, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdNotIn(List<Integer> values) {
            addCriterion("CUR_ACTION_ID not in", values, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdBetween(Integer value1, Integer value2) {
            addCriterion("CUR_ACTION_ID between", value1, value2, "curActionId");
            return (Criteria) this;
        }

        public Criteria andCurActionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CUR_ACTION_ID not between", value1, value2, "curActionId");
            return (Criteria) this;
        }

        public Criteria andBefromIsNull() {
            addCriterion("BEFROM is null");
            return (Criteria) this;
        }

        public Criteria andBefromIsNotNull() {
            addCriterion("BEFROM is not null");
            return (Criteria) this;
        }

        public Criteria andBefromEqualTo(String value) {
            addCriterion("BEFROM =", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromNotEqualTo(String value) {
            addCriterion("BEFROM <>", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromGreaterThan(String value) {
            addCriterion("BEFROM >", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromGreaterThanOrEqualTo(String value) {
            addCriterion("BEFROM >=", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromLessThan(String value) {
            addCriterion("BEFROM <", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromLessThanOrEqualTo(String value) {
            addCriterion("BEFROM <=", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromLike(String value) {
            addCriterion("BEFROM like", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromNotLike(String value) {
            addCriterion("BEFROM not like", value, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromIn(List<String> values) {
            addCriterion("BEFROM in", values, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromNotIn(List<String> values) {
            addCriterion("BEFROM not in", values, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromBetween(String value1, String value2) {
            addCriterion("BEFROM between", value1, value2, "befrom");
            return (Criteria) this;
        }

        public Criteria andBefromNotBetween(String value1, String value2) {
            addCriterion("BEFROM not between", value1, value2, "befrom");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_page
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 03 15:21:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}