package com.demo.druid.model;

import java.util.Date;

public class LogPage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.PAOPID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private Integer PAOPID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.USERID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private String USERID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.USERIP
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private String USERIP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.LAST_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private String LAST_ACTION_ENAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.LAST_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private Integer LAST_ACTION_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.CUR_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private String CUR_ACTION_ENAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.CUR_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private Integer CUR_ACTION_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.BEFROM
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private String BEFROM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.CREATE_TIME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.ID
     *
     * @return the value of log_page.ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.ID
     *
     * @param ID the value for log_page.ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.PAOPID
     *
     * @return the value of log_page.PAOPID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Integer getPAOPID() {
        return PAOPID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.PAOPID
     *
     * @param PAOPID the value for log_page.PAOPID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setPAOPID(Integer PAOPID) {
        this.PAOPID = PAOPID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.USERID
     *
     * @return the value of log_page.USERID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public String getUSERID() {
        return USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.USERID
     *
     * @param USERID the value for log_page.USERID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setUSERID(String USERID) {
        this.USERID = USERID == null ? null : USERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.USERIP
     *
     * @return the value of log_page.USERIP
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public String getUSERIP() {
        return USERIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.USERIP
     *
     * @param USERIP the value for log_page.USERIP
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setUSERIP(String USERIP) {
        this.USERIP = USERIP == null ? null : USERIP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.LAST_ACTION_ENAME
     *
     * @return the value of log_page.LAST_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public String getLAST_ACTION_ENAME() {
        return LAST_ACTION_ENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.LAST_ACTION_ENAME
     *
     * @param LAST_ACTION_ENAME the value for log_page.LAST_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setLAST_ACTION_ENAME(String LAST_ACTION_ENAME) {
        this.LAST_ACTION_ENAME = LAST_ACTION_ENAME == null ? null : LAST_ACTION_ENAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.LAST_ACTION_ID
     *
     * @return the value of log_page.LAST_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Integer getLAST_ACTION_ID() {
        return LAST_ACTION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.LAST_ACTION_ID
     *
     * @param LAST_ACTION_ID the value for log_page.LAST_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setLAST_ACTION_ID(Integer LAST_ACTION_ID) {
        this.LAST_ACTION_ID = LAST_ACTION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.CUR_ACTION_ENAME
     *
     * @return the value of log_page.CUR_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public String getCUR_ACTION_ENAME() {
        return CUR_ACTION_ENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.CUR_ACTION_ENAME
     *
     * @param CUR_ACTION_ENAME the value for log_page.CUR_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setCUR_ACTION_ENAME(String CUR_ACTION_ENAME) {
        this.CUR_ACTION_ENAME = CUR_ACTION_ENAME == null ? null : CUR_ACTION_ENAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.CUR_ACTION_ID
     *
     * @return the value of log_page.CUR_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Integer getCUR_ACTION_ID() {
        return CUR_ACTION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.CUR_ACTION_ID
     *
     * @param CUR_ACTION_ID the value for log_page.CUR_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setCUR_ACTION_ID(Integer CUR_ACTION_ID) {
        this.CUR_ACTION_ID = CUR_ACTION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.BEFROM
     *
     * @return the value of log_page.BEFROM
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public String getBEFROM() {
        return BEFROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.BEFROM
     *
     * @param BEFROM the value for log_page.BEFROM
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setBEFROM(String BEFROM) {
        this.BEFROM = BEFROM == null ? null : BEFROM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.CREATE_TIME
     *
     * @return the value of log_page.CREATE_TIME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.CREATE_TIME
     *
     * @param CREATE_TIME the value for log_page.CREATE_TIME
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}