package com.demo.druid.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogPageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public LogPageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(Integer value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(Integer value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(Integer value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<Integer> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDIsNull() {
            addCriterion("PAOPID is null");
            return (Criteria) this;
        }

        public Criteria andPAOPIDIsNotNull() {
            addCriterion("PAOPID is not null");
            return (Criteria) this;
        }

        public Criteria andPAOPIDEqualTo(Integer value) {
            addCriterion("PAOPID =", value, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDNotEqualTo(Integer value) {
            addCriterion("PAOPID <>", value, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDGreaterThan(Integer value) {
            addCriterion("PAOPID >", value, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("PAOPID >=", value, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDLessThan(Integer value) {
            addCriterion("PAOPID <", value, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDLessThanOrEqualTo(Integer value) {
            addCriterion("PAOPID <=", value, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDIn(List<Integer> values) {
            addCriterion("PAOPID in", values, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDNotIn(List<Integer> values) {
            addCriterion("PAOPID not in", values, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDBetween(Integer value1, Integer value2) {
            addCriterion("PAOPID between", value1, value2, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andPAOPIDNotBetween(Integer value1, Integer value2) {
            addCriterion("PAOPID not between", value1, value2, "PAOPID");
            return (Criteria) this;
        }

        public Criteria andUSERIDIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUSERIDIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUSERIDEqualTo(String value) {
            addCriterion("USERID =", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotEqualTo(String value) {
            addCriterion("USERID <>", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDGreaterThan(String value) {
            addCriterion("USERID >", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLessThan(String value) {
            addCriterion("USERID <", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLike(String value) {
            addCriterion("USERID like", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotLike(String value) {
            addCriterion("USERID not like", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDIn(List<String> values) {
            addCriterion("USERID in", values, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotIn(List<String> values) {
            addCriterion("USERID not in", values, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIPIsNull() {
            addCriterion("USERIP is null");
            return (Criteria) this;
        }

        public Criteria andUSERIPIsNotNull() {
            addCriterion("USERIP is not null");
            return (Criteria) this;
        }

        public Criteria andUSERIPEqualTo(String value) {
            addCriterion("USERIP =", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPNotEqualTo(String value) {
            addCriterion("USERIP <>", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPGreaterThan(String value) {
            addCriterion("USERIP >", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPGreaterThanOrEqualTo(String value) {
            addCriterion("USERIP >=", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPLessThan(String value) {
            addCriterion("USERIP <", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPLessThanOrEqualTo(String value) {
            addCriterion("USERIP <=", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPLike(String value) {
            addCriterion("USERIP like", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPNotLike(String value) {
            addCriterion("USERIP not like", value, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPIn(List<String> values) {
            addCriterion("USERIP in", values, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPNotIn(List<String> values) {
            addCriterion("USERIP not in", values, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPBetween(String value1, String value2) {
            addCriterion("USERIP between", value1, value2, "USERIP");
            return (Criteria) this;
        }

        public Criteria andUSERIPNotBetween(String value1, String value2) {
            addCriterion("USERIP not between", value1, value2, "USERIP");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEIsNull() {
            addCriterion("LAST_ACTION_ENAME is null");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEIsNotNull() {
            addCriterion("LAST_ACTION_ENAME is not null");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME =", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMENotEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME <>", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEGreaterThan(String value) {
            addCriterion("LAST_ACTION_ENAME >", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME >=", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMELessThan(String value) {
            addCriterion("LAST_ACTION_ENAME <", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMELessThanOrEqualTo(String value) {
            addCriterion("LAST_ACTION_ENAME <=", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMELike(String value) {
            addCriterion("LAST_ACTION_ENAME like", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMENotLike(String value) {
            addCriterion("LAST_ACTION_ENAME not like", value, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEIn(List<String> values) {
            addCriterion("LAST_ACTION_ENAME in", values, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMENotIn(List<String> values) {
            addCriterion("LAST_ACTION_ENAME not in", values, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMEBetween(String value1, String value2) {
            addCriterion("LAST_ACTION_ENAME between", value1, value2, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_ENAMENotBetween(String value1, String value2) {
            addCriterion("LAST_ACTION_ENAME not between", value1, value2, "LAST_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDIsNull() {
            addCriterion("LAST_ACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDIsNotNull() {
            addCriterion("LAST_ACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID =", value, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDNotEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID <>", value, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDGreaterThan(Integer value) {
            addCriterion("LAST_ACTION_ID >", value, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID >=", value, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDLessThan(Integer value) {
            addCriterion("LAST_ACTION_ID <", value, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDLessThanOrEqualTo(Integer value) {
            addCriterion("LAST_ACTION_ID <=", value, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDIn(List<Integer> values) {
            addCriterion("LAST_ACTION_ID in", values, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDNotIn(List<Integer> values) {
            addCriterion("LAST_ACTION_ID not in", values, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDBetween(Integer value1, Integer value2) {
            addCriterion("LAST_ACTION_ID between", value1, value2, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_ACTION_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("LAST_ACTION_ID not between", value1, value2, "LAST_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEIsNull() {
            addCriterion("CUR_ACTION_ENAME is null");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEIsNotNull() {
            addCriterion("CUR_ACTION_ENAME is not null");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME =", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMENotEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME <>", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEGreaterThan(String value) {
            addCriterion("CUR_ACTION_ENAME >", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEGreaterThanOrEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME >=", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMELessThan(String value) {
            addCriterion("CUR_ACTION_ENAME <", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMELessThanOrEqualTo(String value) {
            addCriterion("CUR_ACTION_ENAME <=", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMELike(String value) {
            addCriterion("CUR_ACTION_ENAME like", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMENotLike(String value) {
            addCriterion("CUR_ACTION_ENAME not like", value, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEIn(List<String> values) {
            addCriterion("CUR_ACTION_ENAME in", values, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMENotIn(List<String> values) {
            addCriterion("CUR_ACTION_ENAME not in", values, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMEBetween(String value1, String value2) {
            addCriterion("CUR_ACTION_ENAME between", value1, value2, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_ENAMENotBetween(String value1, String value2) {
            addCriterion("CUR_ACTION_ENAME not between", value1, value2, "CUR_ACTION_ENAME");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDIsNull() {
            addCriterion("CUR_ACTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDIsNotNull() {
            addCriterion("CUR_ACTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID =", value, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDNotEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID <>", value, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDGreaterThan(Integer value) {
            addCriterion("CUR_ACTION_ID >", value, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDGreaterThanOrEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID >=", value, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDLessThan(Integer value) {
            addCriterion("CUR_ACTION_ID <", value, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDLessThanOrEqualTo(Integer value) {
            addCriterion("CUR_ACTION_ID <=", value, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDIn(List<Integer> values) {
            addCriterion("CUR_ACTION_ID in", values, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDNotIn(List<Integer> values) {
            addCriterion("CUR_ACTION_ID not in", values, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDBetween(Integer value1, Integer value2) {
            addCriterion("CUR_ACTION_ID between", value1, value2, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andCUR_ACTION_IDNotBetween(Integer value1, Integer value2) {
            addCriterion("CUR_ACTION_ID not between", value1, value2, "CUR_ACTION_ID");
            return (Criteria) this;
        }

        public Criteria andBEFROMIsNull() {
            addCriterion("BEFROM is null");
            return (Criteria) this;
        }

        public Criteria andBEFROMIsNotNull() {
            addCriterion("BEFROM is not null");
            return (Criteria) this;
        }

        public Criteria andBEFROMEqualTo(String value) {
            addCriterion("BEFROM =", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMNotEqualTo(String value) {
            addCriterion("BEFROM <>", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMGreaterThan(String value) {
            addCriterion("BEFROM >", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMGreaterThanOrEqualTo(String value) {
            addCriterion("BEFROM >=", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMLessThan(String value) {
            addCriterion("BEFROM <", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMLessThanOrEqualTo(String value) {
            addCriterion("BEFROM <=", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMLike(String value) {
            addCriterion("BEFROM like", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMNotLike(String value) {
            addCriterion("BEFROM not like", value, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMIn(List<String> values) {
            addCriterion("BEFROM in", values, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMNotIn(List<String> values) {
            addCriterion("BEFROM not in", values, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMBetween(String value1, String value2) {
            addCriterion("BEFROM between", value1, value2, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andBEFROMNotBetween(String value1, String value2) {
            addCriterion("BEFROM not between", value1, value2, "BEFROM");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMEBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }

        public Criteria andCREATE_TIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "CREATE_TIME");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_page
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 03 15:04:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}