package com.demo.druid.model;

import java.util.Date;

public class LogPage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.PAOPID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private Integer paopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.USERID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.USERIP
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private String userip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.LAST_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private String lastActionEname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.LAST_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private Integer lastActionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.CUR_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private String curActionEname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.CUR_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private Integer curActionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.BEFROM
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private String befrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_page.CREATE_TIME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.ID
     *
     * @return the value of log_page.ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.ID
     *
     * @param id the value for log_page.ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.PAOPID
     *
     * @return the value of log_page.PAOPID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Integer getPaopid() {
        return paopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.PAOPID
     *
     * @param paopid the value for log_page.PAOPID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setPaopid(Integer paopid) {
        this.paopid = paopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.USERID
     *
     * @return the value of log_page.USERID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.USERID
     *
     * @param userid the value for log_page.USERID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.USERIP
     *
     * @return the value of log_page.USERIP
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public String getUserip() {
        return userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.USERIP
     *
     * @param userip the value for log_page.USERIP
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setUserip(String userip) {
        this.userip = userip == null ? null : userip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.LAST_ACTION_ENAME
     *
     * @return the value of log_page.LAST_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public String getLastActionEname() {
        return lastActionEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.LAST_ACTION_ENAME
     *
     * @param lastActionEname the value for log_page.LAST_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setLastActionEname(String lastActionEname) {
        this.lastActionEname = lastActionEname == null ? null : lastActionEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.LAST_ACTION_ID
     *
     * @return the value of log_page.LAST_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Integer getLastActionId() {
        return lastActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.LAST_ACTION_ID
     *
     * @param lastActionId the value for log_page.LAST_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setLastActionId(Integer lastActionId) {
        this.lastActionId = lastActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.CUR_ACTION_ENAME
     *
     * @return the value of log_page.CUR_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public String getCurActionEname() {
        return curActionEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.CUR_ACTION_ENAME
     *
     * @param curActionEname the value for log_page.CUR_ACTION_ENAME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setCurActionEname(String curActionEname) {
        this.curActionEname = curActionEname == null ? null : curActionEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.CUR_ACTION_ID
     *
     * @return the value of log_page.CUR_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Integer getCurActionId() {
        return curActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.CUR_ACTION_ID
     *
     * @param curActionId the value for log_page.CUR_ACTION_ID
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setCurActionId(Integer curActionId) {
        this.curActionId = curActionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.BEFROM
     *
     * @return the value of log_page.BEFROM
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public String getBefrom() {
        return befrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.BEFROM
     *
     * @param befrom the value for log_page.BEFROM
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setBefrom(String befrom) {
        this.befrom = befrom == null ? null : befrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_page.CREATE_TIME
     *
     * @return the value of log_page.CREATE_TIME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_page.CREATE_TIME
     *
     * @param createTime the value for log_page.CREATE_TIME
     *
     * @mbg.generated Fri Aug 03 15:21:41 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}