package com.demo.druid.mapper;

import com.demo.druid.model.LogPage;
import com.demo.druid.model.LogPageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    long countByExample(LogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int deleteByExample(LogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int insert(LogPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int insertSelective(LogPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    List<LogPage> selectByExample(LogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    LogPage selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") LogPage record, @Param("example") LogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int updateByExample(@Param("record") LogPage record, @Param("example") LogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int updateByPrimaryKeySelective(LogPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_page
     *
     * @mbg.generated Fri Aug 03 15:04:45 CST 2018
     */
    int updateByPrimaryKey(LogPage record);
}