
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.njqg;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2018-01-05T21:34:54.522+08:00
 * Generated source version: 3.1.0
 * 
 */

@WebService(
                      serviceName = "HelloServiceImplService",
                      portName = "HelloServiceImplPort",
                      targetNamespace = "http://webservice.demo.com/",
                      wsdlLocation = "file:/E:/HelloService.wsdl",
                      endpointInterface = "com.njqg.HelloService")
                      
public class HelloServiceImplPortImpl implements HelloService {

    private static final Logger LOG = Logger.getLogger(HelloServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.njqg.HelloService#sayHello(java.lang.String  name )*
     */
    public String sayHello(String name) {
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
