package com.njqg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2018-01-05T21:34:54.530+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://webservice.demo.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod(action = "say-hello")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.demo.com/", className = "com.njqg.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.demo.com/", className = "com.njqg.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(
            @WebParam(name = "name", targetNamespace = "")
                    String name
    );
}
